name: Detect Patchback Bot Backport Failures

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  detect_backport_failure:
    if: github.event.pull_request.merged == true  # Only run for merged PRs
    runs-on: ubuntu-latest

    steps:
      - name: Check for Patchback Bot Comments
        id: check_comments
        shell: bash
        run: |
          # Fetch PR comments and check if Patchback Bot commented and if it mentions a failure
          comment=$(gh pr view "$PR_NUMBER" -R "$REPO" --comments --json author,body -q '.comments[] | select(.author.login == "patchback" and .body | contains("💔 cherry-picking failed"))')

          # Store the result in an output variable
          if [ -n "$comment" ]; then
            echo "::set-output name=failure_detected::true"
          else
            echo "::set-output name=failure_detected::false"
          fi
        continue-on-error: true

      - name: Add Backport Failed Label
        if: steps.check_comments.outputs.failure_detected == 'true'  # Run only if failure was detected
        shell: bash
        run: |
          # Add the backport_failed label
          gh pr edit ${{ github.event.pull_request.number }} --add-label "backport_failed"
